---
# - name: Change Standard Passwort
#   user:
#     name: pi
#     password: "{{ 'quark'|password_hash('sha512') }}"

- name: Save my SSH key
  authorized_key:
    user: pi
    key: "https://github.com/tumtum.keys"
    state: present
